#github actions 实现代码自动化扫描
name: "Murphysecurity"
description: "Murphysecurity"
author: "Murphysecurity"
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install  CLI
        run: |
          wget -q https://s.murphysec.com/release/install.sh -O - | /bin/bash
      - name: Scan
        run: |
          murphysec scan . --token 98e5c144e91ef72aeebde4ac2a20e963
