name: "MurphySec code scan"
on:
  push:
    branches:
      - main
env:
  MURPHYSEC_TOKEN: ${{ secrets.MURPHYSEC_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: MurphySec code scan
        uses: murphysecurity/actions@v1.0.1
