name: "MurphySec code scan"
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: MurphySec code scan
        uses: murphysecurity/actions@v1.1.0
        with:
          MURPHYSEC_TOKEN: ${{ secrets.MURPHYSEC_TOKEN }}

