#github actions 实现代码自动化扫描
name: "Murphysecurity"
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install  CLI
        run: |
          wget -q https://s.murphysec.com/release/install.sh -O - | /bin/bash
      - name: Scan
        run: |
          echo >results.sarif '{
          "$schema" : "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
          "version" : "2.1.0",
          "runs" :
          [
          {
              "tool" : {
              "driver" : {
                  "name" : "murphysec代码扫描结果"
              }
              },
              "results" : [ {
              "message" : {
                  "text" : "展示漏洞数量",
                  "high" : "666"
              },
              "locations" : [ {
                  "physicalLocation" : {
                  "artifactLocation" : {
                      "uri" : "go.mod"
                  },
                  "region" : {
                      "startLine" : 2,
                      "startColumn" : 7,
                      "endColumn" : 10
                  }
                  }
              } ],
              "partialFingerprints" : {
                  "primaryLocationLineHash" : "39fa2ee980eb94b0:1"
              }
              }]
          }
          ]
          }'
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif


