#github actions 实现代码自动化扫描
name: "Murphysecurity"
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get install -y jq
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install  CLI
        run: |
          wget -q https://s.murphysec.com/release/install.sh -O - | /bin/bash
      - name: Scan
        run: |
          murphysec scan . --token 98e5c144e91ef72aeebde4ac2a20e963 --json >results.json
      - name: Convert to SARIF
        run: |
          jq -c '.' results.json > sarif-report.sarif

      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v2
        with:
          name: sarif-report
          path: sarif-report.sarif
